"""
Central hardware configuration.

Edit wiring and movement constants here so components do not hardcode them.
All Raspberry Pi pin numbers are BCM GPIO numbers.
"""

# Motors - 2x BTS7960 drivers via gpiozero Robot.
MOTOR_LEFT_FWD_PIN = 12
MOTOR_LEFT_BWD_PIN = 13
MOTOR_LEFT_EN_PIN = 5
MOTOR_LEFT_EN_PIN1 = 17

MOTOR_RIGHT_FWD_PIN = 22
MOTOR_RIGHT_BWD_PIN = 23
MOTOR_RIGHT_EN_PIN = 6
MOTOR_RIGHT_EN_PIN1 = 27

MOTOR_PWM_FREQUENCY = 1000

# Water pump relay.
PUMP_PIN = 25
PUMP_ACTIVE_HIGH = False

# Status LEDs - WS2812 / NeoPixel strip.
LED_PIN = 18
LED_COUNT = 8
LED_BRIGHTNESS = 0.20

# Ultrasonic sensor head - ESP32 + HC-SR04 + servo over USB serial.
ULTRASONIC_SERIAL_PORT = "/dev/ttyUSB0"
ULTRASONIC_SERIAL_BAUD = 115200
ULTRASONIC_SERIAL_TIMEOUT = 2.0
ULTRASONIC_OBSTACLE_CM = 20
ULTRASONIC_POLL_INTERVAL = 0.5
ULTRASONIC_SCAN_COOLDOWN = 3.0

# Autonomous obstacle avoidance movement.
ULTRASONIC_AVOID_BACKWARD_SECONDS = 1.0
ULTRASONIC_AVOID_TURN_SECONDS = 0.8
ULTRASONIC_AVOID_FORWARD_SECONDS = 1.2
ULTRASONIC_AVOID_SPEED = 0.5
